apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: spark-do5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: bitnami/postgresql
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_DATABASE
              value: dvdrental
            - name: POSTGRESQL_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: spark-do5
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
