version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodbDO5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  postgres:
    image: postgres:latest
    container_name: postgresDO5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - '5432:5432'


volumes:
  mongo:
  postgres:

